export const FETCHING_POSTS = 'FETCHING_POSTS'
export const GET_INITIAL_DATA = 'GET_INITIAL_DATA'
export const UPDATE_VOTESCORE = 'UPDATE_VOTESCORE'
export const GET_POST_DETAIL = 'GET_POST_DETAIL'

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'
export const UPDATE_VOTESCORE_COMMENT = 'UPDATE_VOTESCORE_COMMENT'